apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: java-demo
  name: deployment-java-demo
spec:
  selector:
    matchLabels:
      app: java-demo
  template:
    metadata:
      labels:
        app: java-demo
    spec:
      containers:
        - image: '192.168.17.1:60080/devops/java-demo'
          name: java-demo
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
          ports:
            - containerPort: 8080
